<?php

	namespace System\Migrations\Inserts;

	use Core\Classes\Database\Database;

	class InsertFaqQuestions202008181016491597785409{

		private $content_array = array();
		private $content_max;

		private $content = 'Curabitur in lacus tempor, vehicula metus rhoncus, pulvinar leo. Proin tincidunt eleifend ipsum eget semper. In nisi sapien, auctor non mi sed, rhoncus mollis lorem. Phasellus consequat fringilla erat eget tristique. Fusce purus quam, consequat eu tristique ut, tempor eu magna. Cras massa risus, tempus at mauris vitae, iaculis pharetra nulla. Aenean facilisis pellentesque ipsum quis posuere. Quisque quis viverra quam. Etiam vitae nisl id sem mollis molestie. Ut risus arcu, euismod quis risus eget, hendrerit porta nisl. Ut euismod pretium tortor, sit amet accumsan felis maximus maximus. Maecenas convallis suscipit eleifend.
Etiam ac leo eget nisi feugiat sagittis sit amet et leo. In hac habitasse platea dictumst. Duis sit amet quam at metus rhoncus sollicitudin quis quis nisi. Vivamus in scelerisque ante. Quisque porttitor, sapien ac mollis iaculis, risus sapien euismod eros, nec aliquet nibh urna ut felis. Integer vitae consectetur ante. Phasellus at scelerisque eros. In tincidunt leo a dolor lobortis, nec consectetur nunc convallis. Integer sed efficitur leo. Nunc bibendum massa ligula, nec euismod mi imperdiet quis. In hac habitasse platea dictumst. Vivamus consectetur porttitor turpis non hendrerit. Morbi viverra pharetra nisl in gravida. Curabitur volutpat odio ut nulla ultricies, in euismod elit mollis.
Vestibulum a consectetur leo. Duis ante leo, ullamcorper nec metus vel, tempus varius sem. Morbi convallis ante at sem consequat, at ornare massa dictum. Suspendisse iaculis vitae velit id tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer gravida dictum ultrices. Nunc dolor diam, cursus porttitor mattis a, tincidunt ac lorem. Donec luctus, ex ac facilisis gravida, urna est porta purus, et tincidunt nisl ligula rhoncus nisl. Pellentesque ut eros mollis, commodo libero in, volutpat lorem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent in suscipit libero, et condimentum lorem. Proin quis pulvinar leo.
Ut a magna consequat, euismod arcu eu, ultrices massa. Aenean non eros luctus, suscipit neque id, cursus tellus. Donec vitae scelerisque purus, vel blandit felis. Praesent nec magna laoreet, congue est at, posuere urna. Etiam finibus interdum justo, in posuere magna maximus ut. Pellentesque ornare nec enim vel rhoncus. Aenean porta felis libero. Praesent efficitur est eget tempor congue. Praesent ut maximus est. Curabitur dui quam, lacinia nec vehicula at, pellentesque sit amet odio. Maecenas consequat lectus lectus. Sed et nisi elementum, cursus nisl faucibus, gravida lacus. Proin dolor elit, lacinia id mollis eu, sagittis id sem. In dignissim pulvinar neque, non venenatis ante mollis a. Donec rhoncus egestas augue non consequat. Quisque quis nulla efficitur, porta metus blandit, rhoncus risus.
Pellentesque dignissim non enim ac vehicula. Suspendisse nec rutrum quam. Cras ornare viverra tortor ac tristique. Aliquam nunc urna, luctus vel nisi vel, dignissim tempus sapien. Donec mattis nibh lobortis, varius ex interdum, laoreet velit. Sed eget luctus mauris. Integer vel nunc nulla. Nulla consectetur massa in tristique interdum. Nulla auctor hendrerit mi, nec posuere sem ultrices sit amet. Vivamus ut sapien quis libero consequat eleifend quis ac arcu. Aenean nec turpis commodo, pretium quam a, imperdiet orci. Vestibulum eget pretium arcu. Integer porttitor tincidunt quam, nec tempor justo mollis quis.
Sed eleifend a nisl quis consequat. Pellentesque eget magna ut ante hendrerit interdum ac eu mauris. Sed blandit imperdiet mollis. Integer vel mi tincidunt, suscipit diam ac, suscipit justo. Morbi lobortis, lectus ut lacinia finibus, quam nunc convallis justo, ac maximus lacus erat ut mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc orci nibh, vulputate at sapien in, porta pretium eros. Vivamus iaculis orci nec est euismod, ut feugiat nisl porta. Sed rutrum blandit elit, sed tincidunt tellus bibendum sed.
Praesent lobortis risus eros, eget mattis velit scelerisque sed. Etiam sit amet quam elit. Fusce eget tellus vel justo varius ullamcorper. Mauris finibus efficitur dui, non convallis lorem maximus a. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas facilisis urna et felis dictum blandit. Cras et mollis urna, quis vulputate neque. Nulla facilisi.
Phasellus non ante ac nunc pharetra mattis id quis nisi. Curabitur laoreet diam nisl, finibus sollicitudin nunc porta at. Quisque finibus erat gravida placerat ultricies. Praesent urna justo, placerat ut leo quis, tristique eleifend sapien. Suspendisse viverra gravida luctus. Aenean sodales quam non ex tincidunt condimentum id vel nisi. Cras nibh ipsum, suscipit in turpis fringilla, condimentum pulvinar lorem. Praesent vel lacinia enim. Morbi maximus erat et efficitur cursus.
Maecenas commodo vulputate condimentum. Duis mattis pharetra urna at pellentesque. Quisque rhoncus condimentum condimentum. Pellentesque ullamcorper purus nec magna venenatis facilisis. Nunc lobortis dui in mi congue, sed elementum est dapibus. Ut ac elit eros. Curabitur tincidunt lorem quis elit sollicitudin, volutpat placerat neque consectetur. Phasellus sit amet ex tortor. In at eleifend erat, at rhoncus urna.
Vestibulum lacinia nulla ut leo tristique faucibus. Sed viverra libero et vulputate faucibus. In vitae sodales enim, eget auctor ipsum. Vestibulum maximus nulla vehicula, iaculis tortor at, finibus mi. Etiam urna elit, dapibus in est a, congue auctor ligula. Suspendisse id convallis enim. Aenean sollicitudin lectus nec rhoncus maximus. Mauris in tempor mi.
Vivamus eu feugiat risus. Morbi maximus cursus est nec vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In aliquam cursus rutrum. Nam sit amet nunc eu felis tincidunt blandit. Aliquam sodales, arcu nec efficitur condimentum, metus tellus laoreet metus, vitae pellentesque massa magna ut justo. Mauris sodales malesuada tortor, in rhoncus orci sagittis eu.
Nulla vel suscipit enim, in lacinia augue. Quisque viverra massa et leo scelerisque, id pharetra nibh tempor. Aliquam porttitor feugiat tristique. Integer eros dolor, feugiat sit amet mattis sit amet, iaculis vel dui. Fusce ac ipsum in nisi hendrerit consequat non in nulla. Mauris consequat posuere ex rutrum vulputate. Donec non dui finibus, tempus dolor eget, vehicula dolor.
Cras elit eros, bibendum in efficitur vitae, pellentesque eget lectus. Aenean tempor mauris in lobortis dictum. Maecenas eget viverra erat. Suspendisse justo nunc, varius non dictum id, tempor et dolor. Donec accumsan, tellus quis interdum porttitor, nunc libero dapibus ante, in posuere libero odio ut purus. Duis interdum ipsum hendrerit, bibendum nulla vel, iaculis est. Nam ut vehicula turpis, nec venenatis quam. Duis ut dui pellentesque, cursus arcu sed, consectetur lectus. Maecenas feugiat diam dignissim, tincidunt risus eu, pharetra est. Cras dictum porttitor fringilla. In consequat, felis sed dignissim fermentum, lorem metus pulvinar magna, nec elementum enim risus a dui. Aliquam posuere, orci a sagittis condimentum, quam massa malesuada nibh, vel tincidunt elit mi malesuada erat.
Nulla mi lacus, placerat a libero vitae, suscipit aliquet urna. Praesent ac rutrum lectus, in pellentesque ante. Suspendisse rhoncus, justo ut consectetur sagittis, justo dui mollis ligula, et sodales nunc mauris imperdiet ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas sed porta felis. Etiam molestie erat nec eleifend euismod. Vivamus imperdiet, massa eget lobortis porta, metus tortor blandit lorem, quis porta nibh ipsum eu risus.
Integer mi odio, hendrerit sit amet turpis quis, lacinia consequat dui. Sed malesuada viverra nisl sed tempor. Curabitur vitae nunc eros. Nunc eu scelerisque dolor. Phasellus mattis dolor vitae tristique fermentum. Proin lacus lectus, ultricies sit amet mattis eleifend, consequat a elit. Integer tincidunt libero arcu, sit amet consequat dolor facilisis at. Fusce in feugiat odio, ut sagittis odio. Aliquam quis ex lobortis, convallis dui convallis, ultricies lacus.
Nulla iaculis libero et arcu aliquet, eu gravida tellus interdum. Duis finibus nunc et accumsan euismod. Vestibulum eleifend ac urna et porttitor. Nullam iaculis suscipit molestie. Etiam in enim condimentum, rhoncus nibh eu, mollis leo. Donec varius sollicitudin metus. In non libero accumsan, feugiat ipsum at, finibus nunc. Etiam at urna eleifend, bibendum felis nec, efficitur ipsum. Sed congue nulla nec sapien elementum gravida. Nullam imperdiet lacus non justo eleifend scelerisque. Quisque consectetur mauris ac venenatis interdum. Aenean ligula sapien, malesuada vel ex at, ultrices facilisis dui. Curabitur velit turpis, imperdiet vitae nisl vitae, lacinia fringilla nisl. Quisque in mi mauris.
Fusce nec facilisis nibh. Curabitur aliquam enim eget turpis bibendum auctor. Proin a ipsum et metus tempus tincidunt. Suspendisse ac justo dui. In sed purus ac ante molestie varius. Fusce sed metus porta, ornare libero eget, tristique felis. Phasellus eget augue tincidunt, viverra elit eget, ultricies libero. Aenean mi mauris, commodo ut turpis ac, blandit dapibus metus. Nulla vitae nibh laoreet, posuere ligula ac, venenatis libero. Fusce ultricies interdum dapibus. Maecenas quis nisi enim.
Aliquam erat volutpat. Integer eu scelerisque neque. Nam felis orci, accumsan id turpis quis, viverra iaculis metus. Nullam pellentesque, turpis quis ultrices convallis, nunc velit auctor eros, et mollis ligula orci ut felis. Donec a dictum odio. Maecenas nec nunc iaculis, feugiat ipsum ut, vehicula nibh. Sed tempus, velit sed sagittis aliquet, neque purus cursus nisi, in vehicula lectus lorem porttitor leo. Etiam pellentesque tristique dolor, eu ornare enim dictum id. Morbi tincidunt a nisi in luctus. Morbi luctus ipsum in sollicitudin semper. Nam sed turpis dui. In hac habitasse platea dictumst.
Maecenas non scelerisque nisi. Maecenas dictum eros et facilisis porta. Integer eget nibh id ex accumsan consectetur vel sit amet urna. In laoreet lectus at enim dignissim, sit amet tristique leo luctus. Vestibulum eget enim id orci varius hendrerit quis vel arcu. Duis finibus sapien id libero tempus, sit amet ultricies lacus pellentesque. In eu efficitur lacus. Curabitur vitae dui a arcu iaculis semper. Nullam eu ipsum ultricies, ornare nisi at, ornare elit. Praesent lobortis sapien vitae dui vestibulum, a tincidunt tellus pulvinar. Sed volutpat est in dui ornare, vel blandit diam ullamcorper.
Nunc euismod dolor massa, quis faucibus elit accumsan ut. Phasellus at nisl non ex elementum dictum sed et mi. Suspendisse consectetur mauris sed velit aliquet tristique. Fusce vehicula mollis condimentum. Sed quis velit ipsum. Nulla facilisi. Suspendisse nec maximus est, vulputate dapibus ipsum. Phasellus arcu neque, interdum non tellus cursus, luctus posuere libero.
Nullam auctor dolor quis lorem vulputate egestas. Donec pellentesque lorem nec porttitor vestibulum. Suspendisse consequat, lectus quis gravida vestibulum, nulla mi finibus dolor, tristique tincidunt diam eros non metus. Cras ut sapien massa. In hac habitasse platea dictumst. Sed posuere elit sed congue lobortis. Nunc vel magna at elit consequat tristique quis vitae purus. Nulla fringilla mauris lorem, eu ullamcorper justo sagittis non. Fusce hendrerit lectus eu ligula consequat, id sollicitudin nisl dictum. Cras eget diam convallis, dapibus odio nec, semper lacus.
Pellentesque auctor viverra arcu, eget tristique arcu iaculis eget. Mauris vitae odio vel dolor varius ultricies nec nec urna. Mauris vulputate mattis condimentum. Maecenas non mauris ut ligula rutrum volutpat. Mauris non congue urna, ac hendrerit quam. Cras suscipit dolor at sagittis feugiat. Etiam ut leo lectus.
Curabitur vitae odio vel metus blandit rhoncus. Curabitur euismod eget mi quis sagittis. Donec ut velit molestie, hendrerit libero eget, fermentum tellus. Curabitur congue sapien tempor consectetur viverra. Integer molestie sagittis ipsum, quis mollis sapien efficitur porta. Etiam urna orci, eleifend a porttitor vel, finibus sed nulla. Vivamus vitae nunc faucibus, porttitor sapien nec, suscipit orci. Suspendisse aliquam purus at magna lacinia, id sollicitudin ante consequat. Sed iaculis tempor nisl a faucibus. Maecenas blandit tempus nibh sit amet pharetra. Etiam eu magna sed tellus congue aliquam sed quis justo. Quisque maximus augue sit amet tortor elementum pretium. Curabitur tincidunt est nec iaculis dapibus. Pellentesque ac ornare mi. Sed in eros ut orci sagittis luctus a quis leo.
Maecenas finibus nibh sit amet enim viverra, eget fermentum mauris bibendum. Curabitur porttitor posuere ante sit amet mollis. Morbi tristique pharetra urna, vitae vehicula quam congue non. Aliquam varius mauris consectetur turpis gravida, lobortis ornare enim finibus. Suspendisse vestibulum velit sit amet leo pellentesque, at posuere justo lobortis. Etiam malesuada, augue vitae fermentum efficitur, felis mi venenatis dolor, ultricies sagittis metus libero in lorem. Duis pellentesque porttitor turpis sed ornare. Aliquam eu nisl massa. Proin nec vestibulum purus. Nam varius arcu ut congue condimentum. Quisque faucibus ultricies ante, sit amet finibus tortor finibus sit amet. Vivamus quis justo ut nulla congue sollicitudin. Maecenas congue non ipsum eu tempus. Pellentesque et congue massa. Nullam eget orci placerat, elementum enim quis, sodales ipsum. Mauris nec scelerisque tortor.
Integer vestibulum vestibulum imperdiet. Pellentesque mollis ipsum vitae lorem commodo pulvinar. Suspendisse posuere libero sed volutpat suscipit. Vestibulum lacus mauris, posuere et fringilla nec, volutpat et mi. Praesent in magna vulputate, commodo felis at, convallis justo. Aenean cursus eros odio, eu efficitur ipsum tristique in. Nulla ac ornare est, sit amet congue arcu. Nunc tempus egestas turpis ut pretium. Nunc nec lectus enim. In maximus feugiat feugiat.
In semper scelerisque dignissim. Integer ut congue arcu. Pellentesque a magna ut magna porta facilisis. Fusce id ante egestas, pharetra nisi ac, facilisis velit. Maecenas in mauris ut ex dignissim sollicitudin. Maecenas vitae nisi efficitur, faucibus leo at, interdum sapien. Vivamus bibendum mollis volutpat. Pellentesque laoreet sit amet nulla vel dapibus. Proin scelerisque condimentum consequat. Sed aliquet elit eget libero aliquet aliquam. Mauris accumsan lectus lorem, at fermentum velit ultrices a. Phasellus accumsan feugiat ligula, eu rutrum arcu interdum at. Phasellus cursus neque sit amet velit aliquet hendrerit. Vestibulum ultricies rutrum est, quis consectetur justo tincidunt ac. Suspendisse id tristique augue.
Praesent varius nisl ac fringilla venenatis. Aenean sed justo lacus. Nam quam mi, malesuada et vulputate in, porttitor venenatis enim. Integer dictum, elit quis lacinia finibus, nisi libero iaculis urna, eget egestas quam magna id magna. Donec posuere orci lacus, sit amet sollicitudin orci pulvinar vitae. Vivamus non est enim. Vivamus dui diam, lacinia sed scelerisque eu, blandit consequat tortor. Integer metus quam, vulputate id iaculis nec, scelerisque et ante. Nunc dignissim lorem quis feugiat pretium. Fusce diam risus, mattis sit amet leo quis, maximus venenatis libero. Aenean aliquet, nibh in pharetra luctus, orci libero pellentesque arcu, quis luctus odio ante ac nunc. Fusce nec sollicitudin augue.
Nulla mollis auctor egestas. Suspendisse hendrerit, erat quis malesuada dictum, tortor nisi auctor tellus, quis sagittis mi ligula quis metus. Aliquam a sodales tortor, at bibendum sem. Aliquam pretium euismod odio, ac luctus felis tempus sed. Praesent vulputate imperdiet sagittis. Duis consectetur egestas felis nec volutpat. Ut commodo ut risus nec pellentesque. Sed tristique in lacus quis faucibus. Etiam accumsan vestibulum ornare. Morbi non arcu blandit, rutrum leo quis, blandit turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque dictum, leo ac viverra gravida, magna orci viverra lorem, quis pulvinar dolor sem ac erat.
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus id ligula nec turpis commodo condimentum sed vel tortor. Integer eu sollicitudin justo. Sed faucibus condimentum dignissim. Donec interdum pretium eros, ut egestas elit volutpat vel. Etiam lacinia sed erat nec semper. Nullam dapibus massa at risus suscipit sagittis. Vivamus eu vulputate turpis, eu semper ligula. Curabitur at nibh aliquam, vestibulum nisi non, mattis diam. Nam efficitur nec metus ac venenatis. Aliquam sed lacus eget neque rhoncus varius in nec leo.
Suspendisse auctor laoreet nisl, et sollicitudin tellus molestie non. Praesent venenatis mauris odio, a sollicitudin turpis aliquet mattis. Nunc id lacinia tellus, eget pellentesque nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum velit sapien, laoreet nec consequat sed, accumsan ac dui. Nullam eleifend leo ut sapien blandit, sit amet sollicitudin metus dapibus. Proin vestibulum tincidunt sapien, sed pulvinar lectus auctor id.
Suspendisse cursus faucibus neque ut posuere. Etiam luctus, metus non placerat semper, lacus augue tincidunt purus, nec suscipit ante nibh vel orci. Curabitur luctus efficitur ex ut viverra. Donec fermentum, tortor vitae condimentum ultrices, erat lacus vulputate sem, a fermentum erat purus sit amet felis. Duis lobortis volutpat erat, a interdum lacus convallis sit amet. Duis ultricies erat lacinia mi vehicula tristique. Maecenas rhoncus scelerisque imperdiet. Fusce auctor, felis eget consectetur euismod, diam lorem facilisis eros, in sodales arcu sapien semper sapien. Integer metus risus, suscipit sed faucibus et, congue cursus orci. Cras nec nisi elit. Etiam hendrerit erat a accumsan malesuada. Ut rutrum, urna eget fringilla semper, lacus purus faucibus odio, nec maximus ligula nisi eget nibh. Duis euismod ipsum ut odio consequat, sit amet commodo est tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent eu quam et tortor tincidunt efficitur. Nunc id nulla ac erat ultricies maximus nec tincidunt est.
Donec nec ultricies augue. Vestibulum elementum laoreet ullamcorper. Donec feugiat viverra risus, et pellentesque quam porttitor non. Mauris laoreet nulla velit, et interdum nisl consectetur quis. Sed congue augue eget velit luctus, a varius purus iaculis. Nam tincidunt consectetur neque vel malesuada. Morbi ullamcorper feugiat metus et suscipit. Duis erat augue, luctus ac lacus nec, volutpat ultricies libero. Nunc euismod diam quis enim lobortis feugiat. Morbi efficitur nulla odio, in blandit metus consequat sed. Duis mollis egestas turpis a commodo. Fusce pharetra, dolor in porttitor accumsan, massa purus pharetra lectus, nec viverra orci tellus eget turpis. Ut condimentum eget mauris a vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut vulputate ante est, facilisis gravida dolor imperdiet in. Aenean commodo eleifend urna, quis eleifend tellus elementum at.
Ut blandit purus ac lectus vestibulum, at condimentum erat vehicula. Nullam dapibus urna in hendrerit ullamcorper. Maecenas laoreet ipsum at velit ornare, et dapibus augue dictum. Proin justo libero, sollicitudin et sodales id, tincidunt ut justo. Etiam mattis diam nibh, eget porta nunc tempor non. Duis elementum est vitae ex tincidunt ultricies. Praesent semper eros est. Sed ultrices velit et sem consequat sollicitudin. Nulla faucibus nisl a ornare bibendum.
Pellentesque scelerisque posuere laoreet. Sed et tortor tincidunt, tempor libero at, cursus ex. Aliquam ac odio ut mi ornare bibendum ut non massa. Curabitur ut lectus condimentum, gravida lectus eget, varius arcu. Morbi magna ligula, suscipit eu diam ac, tempus dignissim erat. Proin gravida lacus sed felis tincidunt imperdiet. Aliquam tristique ipsum ornare augue pulvinar ultrices. Donec semper lacinia scelerisque. Nullam sed odio imperdiet, eleifend orci nec, eleifend arcu.
Vestibulum felis massa, tincidunt eget sapien sed, suscipit tempor nulla. Integer nec vehicula sapien. Etiam tincidunt mi sit amet tellus venenatis sagittis. Nunc rhoncus, ante quis eleifend aliquam, augue enim mollis mi, et feugiat quam nisl id dui. Proin quis luctus orci. Vestibulum sed pharetra lacus. Ut luctus eget tellus et cursus. Integer commodo lobortis est, vel condimentum urna aliquet at. Fusce ac facilisis sem. In tincidunt felis sem, ac imperdiet nunc semper nec. Nulla porttitor ante sit amet lacus rhoncus commodo. Nullam accumsan neque eget tellus accumsan, vitae semper ex feugiat. Ut iaculis varius libero eu elementum. Cras commodo blandit sapien, eu iaculis odio aliquet sed.
Cras et dolor quis ligula tincidunt placerat. Aenean sapien arcu, sodales id orci id, elementum rhoncus dui. Sed ut blandit purus. Nunc mattis eros id massa consectetur, et cursus quam viverra. Quisque sit amet orci sagittis, dignissim dui ornare, semper dolor. Integer consectetur arcu et augue rutrum rutrum. Maecenas efficitur, risus a fringilla condimentum, risus nulla sagittis tortor, nec vulputate purus neque id felis. Maecenas tincidunt ex et aliquet commodo. Curabitur vitae augue tincidunt, sollicitudin ante ut, tristique nulla. Suspendisse potenti. Suspendisse facilisis tempus orci eu rutrum. Donec sed ex posuere quam consectetur suscipit malesuada tempor massa.
Mauris eu leo sit amet neque malesuada pulvinar eget sit amet neque. Fusce luctus convallis sapien at malesuada. Sed eget elit nec lectus malesuada pellentesque a sollicitudin felis. Nulla facilisi. Nullam lacinia pharetra enim quis blandit. Maecenas lacinia libero non iaculis pharetra. Praesent feugiat a ligula vel finibus. Suspendisse vitae metus sed sem vestibulum luctus ac vitae ante.
Maecenas lobortis cursus mi sit amet pellentesque. Fusce sodales risus ut ante blandit iaculis. Nunc tristique arcu lorem, at venenatis risus dignissim sit amet. Duis libero orci, venenatis a tortor id, congue mollis orci. Vestibulum libero elit, lacinia at pulvinar sit amet, pharetra at nisi. Mauris pretium leo sollicitudin sollicitudin sollicitudin. Quisque aliquam mauris ac viverra imperdiet. Integer convallis tellus lorem, eget facilisis risus porttitor sit amet.
Mauris eget sem ligula. Fusce mattis leo at erat dictum, sit amet luctus ligula accumsan. Maecenas et dapibus massa. In nec lorem accumsan, cursus sem ac, dignissim dui. Vivamus sagittis vel diam ac facilisis. Cras varius hendrerit iaculis. Morbi ornare tortor sem, ac efficitur massa ullamcorper ac. Phasellus ut odio semper, rutrum risus non, viverra risus. Proin elementum fringilla ullamcorper. Fusce facilisis lorem vel ante consectetur placerat. Donec vitae nibh nisl. Donec pharetra dapibus diam ut sodales. Aenean tincidunt a dui ac suscipit. Nullam pharetra at lectus sit amet porta. Cras ornare tempor mauris id convallis.
Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut id sem interdum, dictum lacus sed, auctor libero. Integer eleifend egestas nisl ut lacinia. Cras nec nibh mauris. Integer sagittis augue nisi, quis cursus turpis tempor at. Vivamus non molestie felis. Donec viverra, neque ut vulputate scelerisque, velit leo scelerisque elit, non tristique tortor mauris vitae nulla. Quisque et nisl vitae nulla eleifend porta. Aliquam eu metus eu orci aliquet vestibulum. Etiam facilisis augue tortor, et congue turpis elementum non. Donec hendrerit dolor ligula, nec tristique est commodo et. Vestibulum vulputate sit amet orci sit amet dictum. Donec tincidunt consequat nunc sed fermentum.
Aliquam at dui eu turpis sagittis rhoncus sit amet nec quam. Proin et velit pulvinar, vestibulum orci et, eleifend nibh. Quisque in neque ullamcorper, elementum nibh tempus, hendrerit nulla. Etiam ultricies sit amet mauris quis auctor. Quisque venenatis id urna at luctus. Proin vehicula pharetra dictum. Mauris malesuada ultricies leo nec aliquet. Suspendisse potenti. Nam tempus ligula et sollicitudin placerat. Donec quis posuere velit.
Aenean consequat ligula a odio suscipit varius. Aenean consequat at risus vitae maximus. Ut interdum leo enim. Etiam volutpat commodo est, vel lobortis purus sollicitudin in. Vestibulum mollis pellentesque sapien non congue. Integer in pellentesque odio. Ut tincidunt, augue eget interdum consequat, urna nisi dignissim libero, ac maximus lectus risus sed orci.
Integer hendrerit lacus nec arcu ornare consequat. Nunc vehicula aliquam imperdiet. Pellentesque cursus sodales iaculis. Donec rutrum nulla vel turpis porttitor vehicula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras mollis maximus hendrerit. Duis non augue enim. Morbi vitae orci ultricies, tempor erat eleifend, hendrerit est. In non lacus lobortis libero interdum fringilla vitae a turpis.
Maecenas tempus maximus libero eget bibendum. Vestibulum faucibus eros non quam sollicitudin ultrices. Suspendisse quis enim egestas massa condimentum pharetra eget vel lorem. Nunc interdum imperdiet odio eu bibendum. Nam auctor vulputate aliquam. Proin vitae eros urna. Pellentesque scelerisque eleifend eros, vel ornare enim ultrices sed. Duis arcu lorem, scelerisque eu ipsum a, dignissim congue massa. Proin congue magna vitae libero dictum dictum in a purus. Fusce libero nibh, tempor semper viverra sed, ornare vestibulum tellus. In interdum, tellus sit amet vehicula tempor, elit velit posuere odio, ac tempor risus lectus quis sem. Sed gravida interdum odio vitae commodo. Maecenas eget massa commodo, euismod ex vitae, ultricies lorem. Curabitur et tempus metus.
Aliquam dapibus, elit non egestas venenatis, odio ex finibus elit, vitae mattis augue felis eu massa. Fusce pharetra lectus vel sapien mattis rhoncus. Curabitur non lorem at erat gravida efficitur quis a nibh. Nulla placerat ligula nec rhoncus ullamcorper. Fusce lobortis velit at libero consequat, at tempor erat lacinia. Donec luctus faucibus volutpat. Etiam ultrices odio scelerisque interdum blandit. Aenean faucibus erat mauris, ut semper sem lacinia id. Vivamus id dictum velit.
Mauris consectetur lacus nec pulvinar commodo. Aenean semper euismod tellus ut sollicitudin. Nunc sollicitudin justo vel lectus placerat, et gravida libero pretium. Donec ultrices blandit dapibus. Nunc tempor egestas mauris. Sed rutrum, lorem quis vehicula aliquam, eros magna vulputate lectus, eu blandit lorem mi ut quam. Mauris vitae sapien vitae nisi volutpat posuere.
Curabitur non diam et ligula fermentum mollis. Maecenas neque urna, venenatis rutrum quam a, gravida viverra ligula. Nulla et nisl elementum, finibus ipsum pellentesque, luctus augue. Curabitur convallis elementum purus vel eleifend. Aenean pulvinar, sem eu vehicula placerat, sapien risus molestie metus, placerat consectetur odio risus vitae neque. Cras semper cursus efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris at facilisis dui. Sed consectetur leo id accumsan venenatis. Integer ut malesuada ante, nec hendrerit libero. Nam tempus rhoncus posuere. Donec ullamcorper odio libero, ut ullamcorper purus condimentum eu. Nullam eget dui vitae metus dapibus imperdiet non ac augue. Pellentesque id posuere nulla. In venenatis nisl sit amet lectus efficitur facilisis.
Maecenas malesuada dui nulla, in cursus arcu varius quis. Donec sagittis dolor vitae magna tempor, vitae vehicula mauris auctor. Ut eget tempus orci, at semper odio. Donec commodo, elit sed varius ullamcorper, est mauris tincidunt massa, ac consequat risus ex vitae lacus. In nec ultricies urna. Donec lectus justo, fringilla at eleifend a, pulvinar vitae velit. Nullam nec sodales ante. Quisque porttitor purus egestas magna viverra, eget vulputate velit tincidunt. Maecenas in neque tincidunt, vulputate quam sit amet, aliquam erat. Vestibulum at tempor mi. Nulla sit amet erat quis eros pellentesque interdum vel in nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
Sed id diam nec augue egestas congue. Vestibulum rhoncus, justo vel blandit posuere, metus ex maximus ex, rutrum varius elit libero ut risus. Quisque eu dolor bibendum, dapibus tortor ac, elementum est. Pellentesque imperdiet felis id nisl vulputate sodales. Etiam nec gravida justo. Vivamus tempor ornare orci vel aliquet. Etiam volutpat scelerisque magna eget elementum.
Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse facilisis lorem cursus nibh laoreet, ac condimentum metus accumsan. Aliquam egestas quis sem placerat posuere. Vivamus vulputate sagittis diam, ut convallis ipsum. Aliquam ullamcorper pulvinar nunc, vel euismod nunc sollicitudin placerat. Aliquam in molestie turpis. Suspendisse est nulla, sollicitudin ut varius sed, suscipit at lacus.
Curabitur scelerisque, massa quis tincidunt consequat, leo arcu commodo lacus, id dictum quam justo id velit. Suspendisse nec tincidunt ex. Integer dignissim consequat risus interdum luctus. Sed sed malesuada mauris, nec condimentum urna. Nunc varius purus felis, ac dictum felis congue vitae. Aenean lobortis magna in posuere rhoncus. Nam id urna ac dolor tristique malesuada eget tincidunt dolor. Fusce at suscipit mauris. Nullam eu urna turpis. Aliquam sapien tortor, tristique non placerat in, dapibus id orci. Nulla et suscipit nisi. Pellentesque at urna non sem ultricies ultricies. Vivamus sed accumsan massa. Mauris sodales sit amet leo nec congue.
Curabitur luctus nisi non nisl malesuada facilisis. Phasellus sed lacus vel diam fringilla tristique commodo id metus. Maecenas et magna non leo dignissim facilisis sit amet nec erat. In convallis malesuada mi, sed porta magna. Maecenas dolor odio, placerat sollicitudin rhoncus ut, rhoncus in lectus. Donec condimentum augue vitae tortor semper, vel lacinia mauris finibus. Vivamus ultricies nibh non est mollis cursus. Fusce sit amet pretium urna. Suspendisse quis sapien gravida, scelerisque nisi id, commodo nisl. In hac habitasse platea dictumst. Aliquam nulla magna, varius ac erat non, rutrum commodo nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut ut laoreet turpis.
Phasellus ac congue metus, eget auctor leo. Vestibulum cursus ligula sit amet auctor suscipit. Duis vel varius nulla. Integer quis ex quis ipsum auctor feugiat quis sed arcu. In eget feugiat lacus. Aliquam semper lorem nec eros fringilla bibendum. In sit amet cursus nunc. Maecenas congue convallis ex sit amet lobortis. Pellentesque scelerisque orci sapien, id bibendum libero posuere ut.
Ut sed nisi et justo consequat euismod ac sit amet lacus. Aenean pharetra mollis aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis facilisis nisl justo, et condimentum augue consectetur ac. Praesent consequat diam felis, at tincidunt turpis vestibulum eget. Sed hendrerit enim eu eros accumsan, sed scelerisque lectus porttitor. Ut dictum leo vitae tincidunt tristique. Vestibulum varius leo et neque lacinia, sit amet mollis urna tristique. Nulla eu iaculis risus. Integer metus leo, condimentum euismod tellus in, consequat porttitor dolor. Sed accumsan aliquet justo ac commodo.
Morbi quis odio ut metus imperdiet scelerisque. Mauris varius tempor placerat. Nulla ac elementum orci. Nunc ac mauris elit. Duis ullamcorper felis velit, ac finibus nisl semper vel. In sit amet sollicitudin eros. Quisque nulla tellus, consectetur sed leo eu, venenatis mollis ante.';

		public function __construct(){
			$this->setContent();
		}

		public function firstStep(){
			$insert = Database::insert('faq');
			for($i=0;$i<10;$i++){
				$insert = $insert->value('f_question',$this->getContent(rand(0,($this->content_max-1))));
				$insert = $insert->value('f_answer',$this->getContent(rand(0,($this->content_max-1)),rand(3,10)));
			}
			$insert = $insert->get();
			$insert->id();
			return $this;
		}

		private function setContent(){
			$this->content_array = explode('.',$this->content);
			$this->content_max = max(array_keys($this->content_array));
		}

		private function getContent($offset,$limit=1){
			$result = '';
			for($i = $offset;$i < $limit + $offset; $i++){
				$result .= $this->content_array[$i] . ".";
			}
			return $result;
		}










	}