<?php

	return array(
		'controller_name'			=> 'Фотографии',
		'photos_index_title'		=> 'Фотографии',
		'all_photos_sorting'		=> 'Все',
		'created_photos_sorting'	=> 'По загрузке',
		'updated_photos_sorting'	=> 'По обновлению',
		'random_photos_sorting'		=> 'Случайные',
		'photo_updated_in'			=> 'обновлено',
		'show_original_image'		=> 'увеличить',
		'download_original_image'	=> 'скачать',
		'set_image_as_avatar'		=> 'установить на аватар',
		'edit_image'				=> 'изменить',
		'delete_image'				=> 'удалить',
		'download_image_description'=> 'Скачать картинку',
		'photo_added_in'			=> 'добавлено',
		'placeholder_name'			=> 'Имя файла...',
		'placeholder_description'	=> 'Описание файла...',
		'label_name'				=> 'Имя файла',
		'label_description'			=> 'Описание файла',
		'add_photos_button'			=> 'добавить',
		'add_photos_form'			=> 'Добавить фотографии',
		'add_photos'				=> 'Добавить фотографии',
		'select_photos'				=> 'выберите фотографии',
		'delete_link_value'			=> 'убрать',
		'photos_link_title'			=> 'Фотографии',
		'photos_link_value'			=> 'Фотографии',
		'add_new'					=> 'добавить картинок',
	);