<?php

	return array(
		'controller_name'		=> 'Блог',
		'all_posts_sorting'		=> 'Все',
		'my_posts_sorting'		=> 'Мои',
		'created_posts_sorting'	=> 'Новые',
		'updated_posts_sorting'	=> 'Обновленные',
		'random_posts_sorting'	=> 'Случайные',
		'add_new_post'			=> 'создать',
		'my_blog_posts'			=> 'мои записи',
		'edit_blog_post'		=> 'изменить',
		'delete_blog_post'		=> 'удалить',
		'create_blog_post_item'	=> 'Создать новую запись блога',
		'edit_blog_post_item'	=> 'Редактирование',
		'add_new_post_breadcrumb'=> 'Создать запись',
		'edit_new_post_breadcrumb'=> 'Изменить запись',
		'comments_enabled'		=> 'Разрешить комментарии?',
		'item_is_public'		=> 'Запись публичная?',
		'title_field'			=> 'Заголовок',
		'content_field'			=> 'Содержимое',
		'title_field_placeholder'=> 'Пару строк для заголовка...',
		'content_field_placeholder'	=> 'Что Вы хотели рассказать?..',
		'add_image_to_form'		=> 'добавить картинку',
		'blog_link_title'		=> 'Блог',
		'blog_link_value'		=> 'Блог',
		'date_updated_value'	=> 'Обновлено ',
		'attachments_head'		=> 'Закрепленные файлы ',
	);