<?php

	return array(
		'users_index_title'	=> 'Пользователи',
		'users_link_title'	=> 'Пользователи',
		'users_link_value'	=> 'Пользователи',
		'user_is_offline'	=> 'Не в сети',
		'user_is_online'	=> 'В сети',
		'last_visit_date'	=> 'Последний визит',
		'registration_date'	=> 'Дата регистрации',
		'user_groups_list'	=> 'Группы пользователя %full_name%',
		'user_group_'		=> '',
		'user_group_0'		=> '',
		'user_group_guest'		=> 'гость',
		'user_group_user'		=> 'пользователь',
		'user_group_editor'		=> 'редактор',
		'user_group_moder'		=> 'модератор',
		'user_group_admin'		=> 'администратор',

		'user_gender_'		=> '',
		'user_gender_0'		=> '',
		'user_gender_1'		=> 'Мужской',
		'user_gender_2'		=> 'Женский',
		'user_gender_3'		=> 'Не определен',

		'users_index_all_title'		=> 'Все',
		'users_index_online_title'	=> 'В сети',
		'users_index_last_visit_title'	=> 'Последний визит',
		'users_index_offline_title'	=> 'Не в сети',
		'users_index_active_title'	=> 'Подтвержденные',
		'users_index_inactive_title'=> 'Не подтвержденные',
		'users_index_locked_title'	=> 'Приостановленные',
		'users_index_registration_title'	=> 'Регистрация',
		'users_random_title'		=> 'Случайные',
		'users_with_avatar_title'	=> 'С аватарой',

		'users_index_filter_title'	=> 'Фильтр',
		'users_visible_first_name_'	=> 'некто',
		'users_visible_first_name_0'	=> 'некто',
		'users_visible_first_name_1'	=> 'Какой-то',
		'users_visible_first_name_2'	=> 'Какая-то',
		'users_visible_first_name_3'	=> 'Какой-то',
		'users_visible_last_name_'		=> 'никто',
		'users_visible_last_name_0'		=> 'никто',
		'users_visible_last_name_1'		=> 'Неизвестный',
		'users_visible_last_name_2'		=> 'Неизвестная',
		'users_visible_last_name_3'		=> 'Неизвестный',
		'users_visible_full_name_'		=> 'некто никто',
		'users_visible_full_name_0'		=> 'некто никто',
		'users_visible_full_name_1'		=> 'Какой-то Неизвестный',
		'users_visible_full_name_2'		=> 'Какая-то Неизвестная',
		'users_visible_full_name_3'		=> 'Какой-то Неизвестный',

		'first_name'	=> 'Имя',
		'last_name'		=> 'Фамилия',
		'full_name'		=> 'Имя и фамилия',
		'gender'		=> 'Пол',
		'birth_day'		=> 'День рождения',
		'birth_month'	=> 'Месяц рождения',
		'birth_year'	=> 'Год рождения',
		'family'		=> 'Семейное положение',
		'phone'			=> 'Телефон',
		'cophone'		=> 'Доп. телефон',
		'email'			=> 'E-Mail',
		'icq'			=> 'ICQ',
		'skype'			=> 'Skype',
		'viber'			=> 'Viber',
		'whatsapp'		=> 'WhatsApp',
		'telegram'		=> 'Telegram',
		'website'		=> 'Личный сайт',
		'activities'	=> 'Чем занимаюсь',
		'interests'		=> 'Интересы',
		'music'			=> 'Любимая музыка',
		'films'			=> 'Любимые фильмы',
		'shows'			=> 'Любимые телешоу',
		'books'			=> 'Любимые книги',
		'games'			=> 'Любимые игры',
		'citates'		=> 'Любимые цитаты',
		'about'			=> 'О себе',
		'field_set_contacts'	=> 'Контакты',
		'field_set_activities'	=> 'Личное',
		'field_set_name'		=> '',
		'field_set_gender'		=> '',
		'field_set_birth_date'	=> 'Дата рождения',
		'field_set_family'		=> 'Семейное положение',

		'users_family_'		=> '',
		'users_family_0'		=> '',
		'users_family_1'	=> 'состою в браке',
		'users_family_2'	=> 'не состою в браке',
		'users_family_3'	=> 'в активном поиске',
		'users_family_4'	=> 'в разводе',
		'users_family_5'	=> 'никого не ищу',

		'full_name_placeholder'	=> 'Введите имя или фамилию',
		'user_edit_page_value'	=> 'Редактировать',
		'user_page_link_value'	=> 'Моя страница',
		'country'	=> 'Страна',
		'region'	=> 'Регион',
		'city'		=> 'Город',
		'country_placeholder'		=> 'Введите страну',
		'region_placeholder'		=> 'Введите регион',
		'city_placeholder'			=> 'Введите город',

		'edit_profile_link_value'	=> 'Редактировать',
		'header_bar_name'		=> 'Имя',
		'header_bar_geo'		=> 'Страна',
		'header_bar_old'		=> 'Возраст',
		'header_bar_contacts'	=> 'Контакты',
		'header_bar_about'		=> 'О себе',
		'edit_page_title'		=> 'Редактировать страницу',

		'added_status'	=> 'изменить статус',
		'change_status'	=> 'изменить статус',
		'delete_status'	=> 'удалить статус',
		'all_user_photos'	=> 'фото',
	);