<?php

	return array(
		array(
			'command'		=> 'help [structured = false]',
			'class'			=> '\\System\\Console\\Help\\Index',
			'method'		=> 'execute',
			'status'		=> \Core\Classes\Kernel::STATUS_ACTIVE,
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'si',
			'description'	=> 'cli.structure_info',
			'example'		=> 'help 1',
			'section'		=> 'information',
		),
		array(
			'command'		=> 'make table:[table_name]',
			'class'			=> '\\System\\Console\\Make\\DB_Table',
			'method'		=> 'execute',
			'status'		=> \Core\Classes\Kernel::STATUS_ACTIVE,
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'si',
			'description'	=> 'cli.create_migration_table',
			'example'		=> 'make table:users',
			'section'		=> 'database',
		),
		array(
			'command'		=> 'alter table [table_name]:[alter_description]',
			'class'			=> '\\System\\Console\\Make\\DB_Alter',
			'method'		=> 'execute',
			'status'		=> \Core\Classes\Kernel::STATUS_ACTIVE,
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'si',
			'description'	=> 'cli.alter_migration_table',
			'example'		=> 'alter table users:add_users_id_field',
			'section'		=> 'database',
		),
		array(
			'command'		=> 'migrate',
			'class'			=> '\\System\\Console\\Migration\\Run',
			'method'		=> 'execute',
			'status'		=> \Core\Classes\Kernel::STATUS_ACTIVE,
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'si',
			'description'	=> 'cli.run_migrations',
			'example'		=> 'migrate',
			'section'		=> 'database',
		),
		array(
			'command'		=> 'make ctrl:[controller_name]',
			'class'			=> '\\System\\Console\\Make\\Controller',
			'method'		=> 'execute',
			'status'		=> \Core\Classes\Kernel::STATUS_ACTIVE,
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'si',
			'description'	=> 'cli.make_new_controller',
			'example'		=> 'make ctrl:users',
			'section'		=> 'filesystem',
		),
		array(
			'command'		=> 'make class:[Path/To/File]',
			'class'			=> '\\System\\Console\\Make\\Class_File',
			'method'		=> 'execute',
			'status'		=> \Core\Classes\Kernel::STATUS_ACTIVE,
			'pattern'		=> '([a-zа-я0-9-_./]+)',
			'modifier'		=> 'si',
			'description'	=> 'cli.make_standard_class',
			'example'		=> 'make class:Core/Classes/Session',
			'section'		=> 'filesystem',
		),
	);