<?php

	use Core\Classes\Kernel;

	return array(
		array(
			'url'			=> '№[id]',
			'controller'	=> 'users',
			'action'		=> 'item',
			'params'		=> array(),
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'iu',
			'sorting'		=> 1,
			'before'		=> null,
			'after'			=> null,
			'status'		=> Kernel::STATUS_ACTIVE,
		),
		array(
			'url'			=> 'rules',
			'controller'	=> 'blog',
			'action'		=> 'item',
			'params'		=> array(1),
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'iu',
			'sorting'		=> 1,
			'before'		=> null,
			'after'			=> null,
			'status'		=> Kernel::STATUS_INACTIVE,
		),
		array(
			'url'			=> 'faq',
			'controller'	=> 'blog',
			'action'		=> 'item',
			'params'		=> array(2),
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'iu',
			'sorting'		=> 1,
			'before'		=> null,
			'after'			=> null,
			'status'		=> Kernel::STATUS_INACTIVE,
		),
		array(
			'url'			=> 'help',
			'controller'	=> 'blog',
			'action'		=> 'item',
			'params'		=> array(3),
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'iu',
			'sorting'		=> 1,
			'before'		=> null,
			'after'			=> null,
			'status'		=> Kernel::STATUS_INACTIVE,
		),
		array(
			'url'			=> 'support',
			'controller'	=> 'blog',
			'action'		=> 'item',
			'params'		=> array(4),
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'iu',
			'sorting'		=> 1,
			'before'		=> null,
			'after'			=> null,
			'status'		=> Kernel::STATUS_INACTIVE,
		),
		array(
			'url'			=> 'feedback',
			'controller'	=> 'blog',
			'action'		=> 'item',
			'params'		=> array(5),
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'iu',
			'sorting'		=> 1,
			'before'		=> null,
			'after'			=> null,
			'status'		=> Kernel::STATUS_INACTIVE,
		),
		array(
			'url'			=> 'site-news',
			'controller'	=> 'blog',
			'action'		=> 'item',
			'params'		=> array(5),
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'iu',
			'sorting'		=> 1,
			'before'		=> null,
			'after'			=> null,
			'status'		=> Kernel::STATUS_INACTIVE,
		),
		array(
			'url'			=> 'sitemap',
			'controller'	=> 'blog',
			'action'		=> 'item',
			'params'		=> array(7),
			'pattern'		=> '([a-zа-я0-9-_.]+)',
			'modifier'		=> 'iu',
			'sorting'		=> 1,
			'before'		=> null,
			'after'			=> null,
			'status'		=> Kernel::STATUS_INACTIVE,
		),
	);